### ISSUE TITLE
Docker showing exit satus 126

### ISSUE THREAD

**Issue by Mmmattt123** [brewmajsters/timescaledb-docker#1]
## Environment: 
OS: win 10 home
docker: Docker Toolbox v19.03.1

### In docker quickstart terminal type following commands:

0. `> cd /path/to/timescale/dockerfile/folder/` 

1. `> docker build . -t timescale` 

2. `> docker run -d --name brewmasters-timescaledb -p 5432:5432 timescale`

3. `> docker ps -a`

## Output: 
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                        PORTS               NAMES
3fee965e3f39        timescale           "docker-entrypoint.s…"   11 seconds ago      Exited (126) 10 seconds ago                       brewmasters-timescaledb

**Comment by tomas321** [comment]
please, try running the container with this: `docker run -it --name brewmasters-timescaledb -p 5432:5432 timescale` and paste the output here.

**Comment by Mmmattt123** [comment]
$ docker run -it --name brewmasters-timescaledb -p 5432:5432 timescale                                                  The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default timezone ... UTC
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... sh: locale: not found
2020-03-25 10:44:19.731 UTC [29] WARNING:  no usable system locales were found
ok
syncing data to disk ... ok

WARNING: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/data -l logfile start

waiting for server to start....2020-03-25 10:44:20.449 UTC [34] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2020-03-25 10:44:20.463 UTC [35] LOG:  database system was shut down at 2020-03-25 10:44:20 UTC
2020-03-25 10:44:20.466 UTC [34] LOG:  database system is ready to accept connections
2020-03-25 10:44:20.471 UTC [41] LOG:  TimescaleDB background worker launcher connected to shared catalogs
 done
server started

/usr/local/bin/docker-entrypoint.sh: sourcing /docker-entrypoint-initdb.d/000_install_timescaledb.sh
2020-03-25 10:44:20.708 UTC [45] WARNING:
        WELCOME TO
         _____ _                               _     ____________
        |_   _(_)                             | |    |  _  \ ___ \
          | |  _ _ __ ___   ___  ___  ___ __ _| | ___| | | | |_/ /
          | | | |  _ ` _ \ / _ \/ __|/ __/ _` | |/ _ \ | | | ___ \
          | | | | | | | | |  __/\__ \ (_| (_| | |  __/ |/ /| |_/ /
          |_| |_|_| |_| |_|\___||___/\___\__,_|_|\___|___/ \____/
                       Running version 1.6.1
        For more information on TimescaleDB, please visit the following links:

         1. Getting started: https://docs.timescale.com/getting-started
         2. API reference documentation: https://docs.timescale.com/api
         3. How TimescaleDB is designed: https://docs.timescale.com/introduction/architecture

        Note: TimescaleDB collects anonymous reports to better understand and assist our users.
        For more information and how to disable, please see our docs https://docs.timescaledb.com/using-timescaledb/telemetry.

2020-03-25 10:44:20.708 UTC [45] CONTEXT:  PL/pgSQL function inline_code_block line 23 at RAISE
WARNING:
WELCOME TO
 _____ _                               _     ____________
|_   _(_)                             | |    |  _  \ ___ \
  | |  _ _ __ ___   ___  ___  ___ __ _| | ___| | | | |_/ /
  | | | |  _ ` _ \ / _ \/ __|/ __/ _` | |/ _ \ | | | ___ \
  | | | | | | | | |  __/\__ \ (_| (_| | |  __/ |/ /| |_/ /
  |_| |_|_| |_| |_|\___||___/\___\__,_|_|\___|___/ \____/
               Running version 1.6.1
For more information on TimescaleDB, please visit the following links:

 1. Getting started: https://docs.timescale.com/getting-started
 2. API reference documentation: https://docs.timescale.com/api
 3. How TimescaleDB is designed: https://docs.timescale.com/introduction/architecture

Note: TimescaleDB collects anonymous reports to better understand and assist our users.
For more information and how to disable, please see our docs https://docs.timescaledb.com/using-timescaledb/telemetry.

CREATE EXTENSION
2020-03-25 10:44:20.900 UTC [48] WARNING:
        WELCOME TO
         _____ _                               _     ____________
        |_   _(_)                             | |    |  _  \ ___ \
          | |  _ _ __ ___   ___  ___  ___ __ _| | ___| | | | |_/ /
          | | | |  _ ` _ \ / _ \/ __|/ __/ _` | |/ _ \ | | | ___ \
          | | | | | | | | |  __/\__ \ (_| (_| | |  __/ |/ /| |_/ /
          |_| |_|_| |_| |_|\___||___/\___\__,_|_|\___|___/ \____/
                       Running version 1.6.1
        For more information on TimescaleDB, please visit the following links:

         1. Getting started: https://docs.timescale.com/getting-started
         2. API reference documentation: https://docs.timescale.com/api
         3. How TimescaleDB is designed: https://docs.timescale.com/introduction/architecture

        Note: TimescaleDB collects anonymous reports to better understand and assist our users.
        For more information and how to disable, please see our docs https://docs.timescaledb.com/using-timescaledb/telemetry.

2020-03-25 10:44:20.900 UTC [48] CONTEXT:  PL/pgSQL function inline_code_block line 23 at RAISE
WARNING:
WELCOME TO
 _____ _                               _     ____________
|_   _(_)                             | |    |  _  \ ___ \
  | |  _ _ __ ___   ___  ___  ___ __ _| | ___| | | | |_/ /
  | | | |  _ ` _ \ / _ \/ __|/ __/ _` | |/ _ \ | | | ___ \
  | | | | | | | | |  __/\__ \ (_| (_| | |  __/ |/ /| |_/ /
  |_| |_|_| |_| |_|\___||___/\___\__,_|_|\___|___/ \____/
               Running version 1.6.1
For more information on TimescaleDB, please visit the following links:

 1. Getting started: https://docs.timescale.com/getting-started
 2. API reference documentation: https://docs.timescale.com/api
 3. How TimescaleDB is designed: https://docs.timescale.com/introduction/architecture

Note: TimescaleDB collects anonymous reports to better understand and assist our users.
For more information and how to disable, please see our docs https://docs.timescaledb.com/using-timescaledb/telemetry.

2020-03-25 10:44:20.915 UTC [49] WARNING:  telemetry could not connect to "telemetry.timescale.com"
2020-03-25 10:44:20.915 UTC [49] DETAIL:  Interrupted system call
2020-03-25 10:44:20.916 UTC [50] ERROR:  TimescaleDB background worker connected to template database, exiting
2020-03-25 10:44:20.918 UTC [34] LOG:  background worker "TimescaleDB Background Worker Scheduler" (PID 50) exited with exit code 1
CREATE EXTENSION

/usr/local/bin/docker-entrypoint.sh: sourcing /docker-entrypoint-initdb.d/001_reenable_auth.sh

/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/002_timescaledb_tune.sh
Using postgresql.conf at this path:
/var/lib/postgresql/data/postgresql.conf

Writing backup to:
/tmp/timescaledb_tune.backup202003251044

Recommendations based on 989.47 MB of available memory and 1 CPUs for PostgreSQL 11
shared_buffers = 253305kB
effective_cache_size = 759915kB
maintenance_work_mem = 126652kB
work_mem = 1266kB
wal_buffers = 7598kB
min_wal_size = 512MB
default_statistics_target = 500
random_page_cost = 1.1
checkpoint_completion_target = 0.9
max_locks_per_transaction = 64
autovacuum_max_workers = 10
autovacuum_naptime = 10
effective_io_concurrency = 200
timescaledb.last_tuned = '2020-03-25T10:44:20Z'
timescaledb.last_tuned_version = '0.8.0'
Saving changes to: /var/lib/postgresql/data/postgresql.conf

/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/setup_timescaledb.sh
/usr/local/bin/docker-entrypoint.sh: /docker-entrypoint-initdb.d/setup_timescaledb.sh: /bin/bash^M: bad interpreter: No such file or directory

**Comment by tomas321** [comment]
I replicated your scenario and all works for me, I hope the hosting operation system has no impact on the outcome.. Do you have the latest master checkout of the repository?

**Comment by tomas321** [comment]
**/bin/bash^M**: bad interpreter: No such file or directory

from this i suspect you modified the `setup_timescaledb.sh` file.. check for possible interpreter changes.. because the previous setup scripts have completed successfully with the `/bin/bash` interpreter

**Comment by Mmmattt123** [comment]
File `setup_timescaledb.sh` is without changes. I just tried to pull repository again and still got the same exit status.

**Comment by tomas321** [comment]
The issue is in the carriage-return character set by your Windows machine. b2bda0f5c25f3e6597fe26a978f97bdac3050423 fixes the carriage return incompatibility. please verify the fix on your side

**Comment by tomas321** [comment]
if the provided `.gitattributes` file overriding the eol character does not fix the problem, configure it locally in your repository clone directory `git config core.eol=lf` since the Docker image/container is based on linux OS.
